### ISSUE TITLE
Namesake

### ISSUE THREAD

**Issue by AlexBrunetti** [lovc21/NeuroSpeed#1]
Hi,
please note that Nero has been already used for a note chess engine; please consider that, to avoid confusion.

https://www.chessprogramming.org/Nero

Thanks,
Alex

**Comment by lovc21** [comment]
Hey Alex,

Thanks for the heads up! I will consider changing the name to something else.

P.S. How did you find this repo so quickly?

**Comment by AlexBrunetti** [comment]
I found it because I look for new chess engines very often :)

Alex
